Fix log-level option
icloud-photos-downloader/icloud_photos_downloader pull request #194
Opened 2020-10-28 00:37 UTC by ltm

The log level is set on the logger instance in `icloudpd.base.main` based on the `--log-level` option, but subsequent calls to `setup_logger()` resets the level to `DEBUG`. As a result the `--log-level` option is effectively ignored.

Since the `--log-level` option defaults to `DEBUG` it's safe to remove `logger.setLevel()` from `setup_logger()` which allows the option to work as expected.

2020-10-28 06:15 UTC, menkej commented
Hi @ltm !
Thanks for your pull request! The change looks rather simple. I'll test it later.

Can you also add a test case that checks the logging handling?

2020-10-29 00:33 UTC, ltm commented
@menkej I've updated the existing `test_log_levels` test to check for the appropriate levels in the output. For some reason an unrelated test (i.e. `test_until_found`) has started failing, but I see it's failing in other PRs as well so I think it's unrelated to my changes.

2020-10-29 09:38 UTC, menkej requested changes
Thanks updating the test cases! I'l request one additional check: Both tests assume the logger running on INFO. There should also be a test for DEBUG level as well, what do you think?

2020-10-29 09:39 UTC, menkej commented
test_until_found is an issue of its own. It behaves inconsistent (I think we have a PR for that already). I have no Idea why it sometimes runs fine and sometimes does not...

2020-10-29 17:07 UTC, ltm commented
@menkej Makes sense. I've updated (and refactored) the test to check all three log levels.

2020-10-29 18:23 UTC, menkej reviewed
Nice work @ltm! Way better than before. Last little cream on the cake is to add this fix to the CHANGELOG.md in the unreleased section as "fix:" and then we're ready to merge! Sorry I forgot to mention this before. We just introduced the CHANGELOG recently and I'm still not used to it... ;-)

2020-10-30 00:01 UTC, ltm commented
@menkej No problem. I've added a changelog entry.

2020-10-30 06:13 UTC, menkej approved these changes

2020-10-30 06:13 UTC, merged