Add command line arguments to filter by date.
icloud-photos-downloader/icloud_photos_downloader pull request #779
Opened 2024-01-28 19:03 UTC by asriraman

With the new arguments --date-before and --date-after, user can choose to only download items that are created either before, after, or before and after the specified dates. Dates are assumed to be specified in the local timezone.

This should address issue #466, something I have also wanted for a while! 

Comments / suggestions welcome.

2024-01-30 02:13 UTC, wasabhi93 commented on src/icloudpd/base.py
> +@click.option("--date-before",
Agreed, `created-before`  and `created-after` is much more direct and readable! updating.

2024-02-04 18:35 UTC, wasabhi93 commented
@AndreyNikiforov should be ready for re-review

2024-02-04 18:47 UTC, AndreyNikiforov requested changes

2024-02-04 18:47 UTC, AndreyNikiforov commented on tests/test_download_photos.py
> +        assert sum(1 for _ in files_in_result) == 0, "No files should have been downloaded."
pls adjust the test to have a set of files to download with different created dates and then "cut" that set with your new parameter. Confirm that only desired portion of the set is downloaded. That should confirm that criteria filtering is correct and test itself is not broken (as it downloads some files).

There should be tests that validate filters in this manner.

2024-02-07 17:06 UTC, AndreyNikiforov commented on src/icloudpd/base.py
> +            if created_before and created_date > created_before:
These are the conditions we need to validate with a test. Parameter absence is tested, but comparison is not completely validated IMO - need to check we indeed leave some assets and filter out others (assets created on the same date as parameter is the case that should be present in tests as well). In e2e tests that will be translated into checking that some files are downloaded and some are not.

2024-08-23 18:14 UTC, mrsilver76 commented
@itwasabhi Is there any chance you can do the changes requested? It's a useful feature so thank you for developing it.

2024-08-25 23:37 UTC, itwasabhi commented
@mrsilver76 Sure, please give me a week or so to sync to head and make the requested changes!

2024-10-27 16:32 UTC, fliespl commented
@itwasabhi do you think you will get back to it somewhere in the future :) ? This would a game-changer for date based deletion.

2024-12-22 22:10 UTC, mrsilver76 commented
@itwasabhi Is there any chance you can make the changes requested by the code review?

I ask because I'm trying to create an automated process to download photos from iCloud and then group and move them elsewhere. As I don't keep the files in their original download location, I need some way to tell icloudpd not to download photos any earlier than the date the process was last run.   

Thank you!

2025-05-10 14:41 UTC, AndreyNikiforov requested changes
pls adjust the test to have a set of files to download with different created dates and then "cut" that set with your new parameter. Confirm that only desired portion of the set is downloaded. That should confirm that criteria filtering is correct and test itself is not broken (as it downloads some files).

There should be tests that validate filters in this manner.

2025-07-07 18:12 UTC, Grayknife commented
I would love to see that feature as well!

2026-05-21 07:48 UTC, closed without merging